name: SnowflakeDemo
description: ''
version: '3.01'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/demo-jpb:
    name: demo-jpb
    description: ''
    fabricUID: 9957
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/10 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-02-28 10:11:36'
    author: poojas+demo@prophecy.io
  jobs/demo-composer:
    name: demo-composer
    description: ''
    fabricUID: 9960
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/10 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-02-28 10:27:05'
    author: poojas+demo@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-28 10:03:14'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customer_orders:
    name: customer_orders
    schema:
      providerType: Snowflake
      fields:
      - name: TOTAL_ORDERS
        dataType:
          type: Number
      - name: TOTAL_AMOUNT
        dataType:
          type: Number
      - name: FULL_NAME
        dataType:
          type: String
      - name: CUSTOMER_ID
        dataType:
          type: Number
    description: null
    author: poojas+demo@prophecy.io
    files:
    - models/customer_orders.sql
    - .prophecy/ide/models/customer_orders.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-02-28 10:05:10'
sqlSnapshots: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/POOJA_POOJA_ANALYTICS:
    name: POOJA.POOJA_ANALYTICS
    description: null
    author: poojas+demo@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-02-28 10:05:22'
    tables:
    - name: CUSTOMERS
      schema:
        providerType: snowflake
        fields: []
      description: null
      author: poojas+demo@prophecy.io
      createdAt: '2024-02-28 10:05:22'
    - name: STG_CUSTOMERS
      schema:
        providerType: snowflake
        fields: []
      description: null
      author: poojas+demo@prophecy.io
      createdAt: '2024-02-28 10:05:27'
    - name: STG_ORDERS
      schema:
        providerType: snowflake
        fields: []
      description: null
      author: poojas+demo@prophecy.io
      createdAt: '2024-02-28 10:05:31'
  .prophecy/metadata/sqlsources/POOJA_STRIPE:
    name: POOJA.STRIPE
    description: null
    author: poojas+demo@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-02-28 10:05:38'
    tables:
    - name: PAYMENT
      schema:
        providerType: snowflake
        fields: []
      description: null
      author: poojas+demo@prophecy.io
      createdAt: '2024-02-28 10:05:38'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: poojas+demo@prophecy.io
  createdAt: '2024-02-28 10:03:14'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
