WITH PAYMENT AS (

  SELECT * 
  
  FROM {{ source('POOJA.STRIPE', 'PAYMENT') }}

),

STG_CUSTOMERS AS (

  SELECT * 
  
  FROM {{ source('POOJA.POOJA_ANALYTICS', 'STG_CUSTOMERS') }}

),

STG_ORDERS AS (

  SELECT * 
  
  FROM {{ source('POOJA.POOJA_ANALYTICS', 'STG_ORDERS') }}

),

by_CUSTOMER_ID AS (

  SELECT 
    STG_ORDERS.ORDER_ID AS ORDER_ID,
    STG_ORDERS.ORDER_DATE AS ORDER_DATE,
    STG_ORDERS.STATUS AS STATUS,
    STG_CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
    STG_CUSTOMERS.FIRST_NAME AS FIRST_NAME,
    STG_CUSTOMERS.LAST_NAME AS LAST_NAME
  
  FROM STG_ORDERS
  INNER JOIN STG_CUSTOMERS
     ON STG_ORDERS.CUSTOMER_ID = STG_CUSTOMERS.CUSTOMER_ID

),

payment_and_customer_details AS (

  SELECT 
    in0.ID AS ID,
    in0.ORDERID AS ORDERID,
    in0.PAYMENTMETHOD AS PAYMENTMETHOD,
    in0.STATUS AS STATUS,
    in0.AMOUNT AS AMOUNT,
    in0.CREATED AS CREATED,
    in1.ORDER_DATE AS ORDER_DATE,
    in1.CUSTOMER_ID AS CUSTOMER_ID,
    in1.FIRST_NAME AS FIRST_NAME,
    in1.LAST_NAME AS LAST_NAME
  
  FROM PAYMENT AS in0
  INNER JOIN by_CUSTOMER_ID AS in1
     ON in0.ORDERID = in1.ORDER_ID

),

Reformat_1 AS (

  SELECT 
    ORDERID AS ORDERID,
    PAYMENTMETHOD AS PAYMENTMETHOD,
    STATUS AS STATUS,
    AMOUNT AS AMOUNT,
    CREATED AS CREATED,
    ORDER_DATE AS ORDER_DATE,
    CUSTOMER_ID AS CUSTOMER_ID,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME
  
  FROM payment_and_customer_details AS in0

),

Filter_1 AS (

  SELECT * 
  
  FROM Reformat_1 AS in0
  
  WHERE STATUS != 'fail'

),

Aggregate_1 AS (

  SELECT 
    COUNT(DISTINCT ORDERID) AS TOTAL_ORDERS,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    any_value(FULL_NAME) AS FULL_NAME,
    any_value(CUSTOMER_ID) AS CUSTOMER_ID
  
  FROM Filter_1 AS in0
  
  GROUP BY CUSTOMER_ID

)

SELECT *

FROM Aggregate_1
